"""Calendar registry for the 18 rankings shown on India Monitor.

check_months: 1-12. check_day is optional (used with ±7 day tolerance and
a first-week-of-next-month catch-up so the monthly cron still hits dated releases).
fetcher: name of a function in rankings_fetchers, or None for a stub candidate.
"""

INDEXES = [
    {
        "slug": "aqi",
        "name": "World Air Quality Report (PM2.5)",
        "category": "environment",
        "source_publisher": "IQAir",
        "source_url": "https://www.iqair.com/world-most-polluted-countries",
        "check_months": [3],
        "fetcher": "fetch_aqi",
    },
    {
        "slug": "ccpi",
        "name": "Climate Change Performance Index",
        "category": "environment",
        "source_publisher": "Germanwatch / NewClimate Institute / CAN",
        "source_url": "https://ccpi.org/ranking/",
        "check_months": [11, 12],
        "fetcher": None,
    },
    {
        "slug": "cpi",
        "name": "Corruption Perceptions Index",
        "category": "governance",
        "source_publisher": "Transparency International",
        "source_url": "https://www.transparency.org/en/cpi",
        "check_months": [1, 2],
        "fetcher": "fetch_cpi",
    },
    {
        "slug": "epi",
        "name": "Environmental Performance Index",
        "category": "environment",
        "source_publisher": "Yale & Columbia Universities",
        "source_url": "https://epi.yale.edu/",
        "check_months": [6, 7],
        "fetcher": None,
    },
    {
        "slug": "firepower",
        "name": "Global Firepower Index",
        "category": "security",
        "source_publisher": "Global Firepower",
        "source_url": "https://www.globalfirepower.com/countries-listing.php",
        "check_months": [1],
        "fetcher": None,
    },
    {
        "slug": "gdp",
        "name": "GDP size (nominal)",
        "category": "economy",
        "source_publisher": "IMF",
        "source_url": "https://www.imf.org/external/datamapper/NGDPD@WEO/OEMDC/ADVEC/WEOWORLD",
        "check_months": [4, 10],
        "fetcher": None,
    },
    {
        "slug": "gggi",
        "name": "Global Gender Gap Index",
        "category": "human-development",
        "source_publisher": "World Economic Forum",
        "source_url": "https://www.weforum.org/publications/global-gender-gap-report-2025/",
        "check_months": [6, 7],
        "fetcher": None,
    },
    {
        "slug": "ghi",
        "name": "Global Hunger Index",
        "category": "human-development",
        "source_publisher": "Concern Worldwide / Welthungerhilfe",
        "source_url": "https://www.globalhungerindex.org/ranking.html",
        "check_months": [10],
        "fetcher": "fetch_ghi",
    },
    {
        "slug": "gii",
        "name": "Global Innovation Index",
        "category": "innovation",
        "source_publisher": "WIPO",
        "source_url": "https://www.wipo.int/web/global-innovation-index",
        "check_months": [9],
        "fetcher": "fetch_gii",
    },
    {
        "slug": "gii-undp",
        "name": "Gender Inequality Index",
        "category": "human-development",
        "source_publisher": "UNDP",
        "source_url": "https://hdr.undp.org/data-center/thematic-composite-indices/gender-inequality-index",
        "check_months": [3],
        "fetcher": None,
    },
    {
        "slug": "gpi",
        "name": "Global Peace Index",
        "category": "security",
        "source_publisher": "Institute for Economics & Peace",
        "source_url": "https://www.visionofhumanity.org/maps/#/",
        "check_months": [6],
        "fetcher": None,
    },
    {
        "slug": "happiness",
        "name": "World Happiness Report",
        "category": "human-development",
        "source_publisher": "UN SDSN",
        "source_url": "https://worldhappiness.report/",
        "check_months": [3],
        "check_day": 20,
        "fetcher": "fetch_happiness",
    },
    {
        "slug": "hdi",
        "name": "Human Development Index",
        "category": "human-development",
        "source_publisher": "UNDP",
        "source_url": "https://hdr.undp.org/data-center/human-development-index",
        "check_months": [3, 12],
        "fetcher": None,
    },
    {
        "slug": "lpi",
        "name": "Logistics Performance Index",
        "category": "economy",
        "source_publisher": "World Bank",
        "source_url": "https://lpi.worldbank.org/international/global",
        "check_months": [6],
        "fetcher": None,
    },
    {
        "slug": "passport",
        "name": "Henley Passport Index",
        "category": "global-standing",
        "source_publisher": "Henley & Partners",
        "source_url": "https://www.henleyglobal.com/passport-index/ranking",
        "check_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "fetcher": "fetch_passport",
    },
    {
        "slug": "press",
        "name": "World Press Freedom Index",
        "category": "governance",
        "source_publisher": "Reporters Without Borders",
        "source_url": "https://rsf.org/en/index",
        "check_months": [5],
        "check_day": 3,
        "fetcher": "fetch_press",
    },
    {
        "slug": "rol",
        "name": "Rule of Law Index",
        "category": "governance",
        "source_publisher": "World Justice Project",
        "source_url": "https://worldjusticeproject.org/rule-of-law-index/",
        "check_months": [10],
        "fetcher": None,
    },
    {
        "slug": "softpower",
        "name": "Global Soft Power Index",
        "category": "global-standing",
        "source_publisher": "Brand Finance",
        "source_url": "https://brandfinance.com/insights/global-soft-power-index",
        "check_months": [2, 3],
        "fetcher": None,
    },
]


def by_slug(slug):
    for item in INDEXES:
        if item["slug"] == slug:
            return item
    return None
